# @package _global_
defaults:
  - /datamodule: mnist
  - /litmodule: classify_mnist
  - override /hydra/launcher: local
  - _self_
hydra:
  launcher:
    cpus_per_task: 4
config:
  device: cpu
litmodule:
  nnmodule:
    activation_fn:
      _target_: torch.nn.ReLU
    config:
      dims: [784, 128, 10]
  optimizer:
    lr: 0.002
logger:
  entity: maximilienlc
trainer:
  max_epochs: 3
